version: '3.8'  # เวอร์ชันมาตรฐาน

services:
  web:          # ตั้งชื่อบริการว่า 'web'
    build: .    # ให้สร้าง Image จาก Dockerfile ที่อยู่ตรงนี้ (.)
    ports:
      - "80:80" # เจาะรู (Mapping Port)
    container_name: my-smart-container # ตั้งชื่อ Container
    depends_on:
      - api
  api:
    build: ./backend
    ports:
      - "3002:3002"
    container_name: my-backend
    environment:
      - DB_HOST=mongo
    depends_on:
      - mongo
  mongo:
    image: mongo:lastest
    container_name: my-database
    restart: always
    volumes:
      - mongo_data:/data/db
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: always
    ports:
      - "9443:9443"  # ใช้ Port นี้เข้าหน้าเว็บ (HTTPS)
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock  # อนุญาตให้คุยกับ Docker ในเครื่องได้
      - portainer_data:/data # สร้างถังเก็บข้อมูลถาวร (Password จะได้ไม่หาย)

# สร้างถังเก็บข้อมูล (Volume)
volumes:
  portainer_data:
  mongo_data